# 第五章 语句

## 简单语句

- 表达式语句：一个表达式末尾加上分号。
- 空语句：只有一个单独的分号。
- 复合语句（块）：用花括号`{}`包裹起来的语句和声明的序列。

## 条件语句

- 在嵌套的`if-else`语句中，`else`将匹配离它最近的没有配对的`if`，以消除二义性。
- `switch`语句中，`case`与其对应的值一起被称为`case`标签，它必须为整型常量表达式。

## 迭代语句
 
- 当不确定到底要迭代多少次时，使用 `while`循环比较合适，比如读取输入的内容。
- `for`语句可以省略掉`init-statement`，`condition`和`expression`的任何一个，甚至全部。
- C++11引入了范围`for`语句，形式为`for (declaration : expression) statement`。

## 跳转语句

- `break`语句负责终止离它最近的`while`、`do while`、`for`或者`switch`语句，并从这些语句之后的第一条语句开始继续执行。
- `continue`语句则将终止最近的循环中的当前迭代并立即开始下一次迭代，它只能在`while`、`do while`、`for`循环的内部使用。

## try语句块和异常处理

- C++中的异常处理包括：
  - `throw`表达式：异常检测部分使用`throw`表达式来引发一个异常；
  - `try`语句块：异常处理部分使用`try`语句块处理异常，其后是一个或多个`catch`子句。
    - `catch`子句由`catch`、异常声明及一个块组成，块中包含了异常处理代码。
    - `try`语句块中的代码抛出的异常通常会被某个`catch`捕获并处理。
  - 异常类：用于在 `throw`表达式和相关的 catch`子句之间传递异常的具体信息。
- 出现异常时，没有找到任何匹配的`catch`子句，程序将转到名为`terminate`的标准库函数，从而导致程序异常退出。
- 进行异常处理过程如下例所示：

  ``` cpp
  while (cin >> item1 >> item2) {
      try { // try语句
          if (item1.isbn() != item2.isbn()) {
              throw runtime_error("Data must refer to same ISBN"); // 抛出异常
          } 
      } catch (runtime_error err) { // catch子句，捕获异常
          cout << err.what() << "\nTry Again? Enter y or n" << endl; // 处理异常
          char c;
          cin >> c;
          if (!cin || c == 'n') {
              break;
          }
      }
  }
  ```

### 标准异常

- 标准库中的异常类定义在4个头文件中：
  - `<exception>`：包含最常见的异常类`exception`，只报告异常发生，不提供其他信息；
  - `<stdexcept>`：定义了几种常用异常类:
    - `exception`：最常见问题；
    - `runtime_error`：运行时问题；
    - `range_error`：运行时，结果超出有意义的值域范围；
    - `overflow_error`：运行时，上溢；
    - `underflow_error`：运行时，下溢；
    - `logic_error`：程序逻辑错误；
    - `domain_error`：逻辑，参数对应结果值不存在；
    - `invalid_error`：逻辑，无效参数；
    - `length_error`：逻辑，试图创建超出类型最大长度的对象；
    - `out_of_range`：逻辑，使用超出有效范围的值；
  - `<new>`：定义了`bad_alloc`异常类；
  - `<type_info>`：定义了`bad_cast`异常类。
- 其中：
  - `exception`、`bad_alloc`、`bad_cast`对象只能默认初始化，其他异常类必须用`string`或`C风格字符串`进行初始化。
  - 异常类型只定义了成员函数`what`，该函数无参数，返回类型为`const char*`的异常提示信息；对无初始值的异常，返回的值由编译器决定。